// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspNetCoreEscuela.Models;

#nullable disable

namespace aspNetCoreEscuela.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20220606013432_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("aspNetCoreEscuela.Models.Alumno", b =>
                {
                    b.Property<Guid>("AlumnoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CursoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AlumnoID");

                    b.HasIndex("CursoID");

                    b.ToTable("Alumno", (string)null);

                    b.HasData(
                        new
                        {
                            AlumnoID = new Guid("00a7c497-cb20-406a-84ae-52a8c9a4a9d5"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Alvaro Diomedes Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("00c9a798-79fe-41cf-bcb3-aa5c6fabce0f"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Alba Murty Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("00e9cb2d-e4a9-4ec9-b5c1-7ea6861c4614"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Nicolás Rick Uribe"
                        },
                        new
                        {
                            AlumnoID = new Guid("00f1e99d-da55-4b8d-9e10-c3b7ed492059"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Donald Silvana Maduro"
                        },
                        new
                        {
                            AlumnoID = new Guid("0145ec89-82c7-46d1-ac27-123ad641479e"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Alba Anabel Maduro"
                        },
                        new
                        {
                            AlumnoID = new Guid("019079b2-6477-4765-b65f-821700420098"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Alvaro Nicomedes Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("01a9ce10-1d48-45b2-8de5-a2c7f7484e35"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Felipa Rick Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("02765a09-f944-4df9-9c28-65d04cc73802"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Alba Teodoro Trump"
                        },
                        new
                        {
                            AlumnoID = new Guid("00638cc2-ca61-40a0-9466-896868376ffe"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Donald Rick Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("019aeca0-fa98-45f9-b7eb-f33ca28a5a51"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Alba Freddy Uribe"
                        },
                        new
                        {
                            AlumnoID = new Guid("01efcb6f-2bc4-43f3-8a69-5ceeed0b5e87"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Felipa Anabel Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("0264cf60-b299-4e8a-84c8-54e36dd1ea19"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Eusebio Silvana Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("03137c50-3f25-415e-9918-1d04c7b37b85"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Farid Anabel Uribe"
                        },
                        new
                        {
                            AlumnoID = new Guid("0541c2ae-5d4d-4374-b560-e53be7a1f8fc"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Donald Diomedes Uribe"
                        },
                        new
                        {
                            AlumnoID = new Guid("058a8922-793a-460c-8079-a87b96a181f3"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Nicolás Murty Uribe"
                        },
                        new
                        {
                            AlumnoID = new Guid("05ee5723-cc17-458f-af1e-5a44dbc63d50"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Alba Anabel Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("0645670a-d209-4a90-9176-3232af1bd408"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Alba Silvana Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("07cb4f94-5315-46f8-a8be-c702b00dedf9"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Donald Silvana Trump"
                        },
                        new
                        {
                            AlumnoID = new Guid("005f1a9b-4eb2-442b-9e89-d4d6740c9f99"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Farid Silvana Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("00e4f2a8-b238-4ce0-b566-761c441ea8ce"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Alvaro Anabel Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("01437c47-df3a-4252-9074-32f44b99dde8"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Nicolás Freddy Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("0143f4e8-5f47-47e0-acdd-1c172a66dae6"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Felipa Anabel Uribe"
                        },
                        new
                        {
                            AlumnoID = new Guid("015a9585-83aa-475e-8ce8-5859dabc2ff4"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Alba Murty Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("01e02c82-27d2-45f0-ab8d-d63ce5f2cd17"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Eusebio Teodoro Uribe"
                        },
                        new
                        {
                            AlumnoID = new Guid("020ce23d-9e99-4012-9d56-0320147659ca"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Alba Diomedes Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("022df560-ea6f-4ff2-bcc7-6f43ddf24018"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Farid Silvana Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("025b3e1e-403e-4505-a6c9-e8ba5a961a93"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Alvaro Freddy Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("02a01ce4-024f-47d0-8087-e8d6aeb1f79e"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Farid Teodoro Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("04464771-3845-4918-9c95-1ecf95012d30"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Alvaro Nicomedes Trump"
                        },
                        new
                        {
                            AlumnoID = new Guid("0518342e-5f9b-4a02-9080-1f9a25dadd9c"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Alvaro Diomedes Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("05d060d4-ab7f-4808-b8dc-d7b9e2d03ce5"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Donald Teodoro Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("07180cd1-fb9f-4a39-84f6-d8c182c96041"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Farid Murty Maduro"
                        },
                        new
                        {
                            AlumnoID = new Guid("07ad9359-8a60-41f8-8b83-e453a0f691f2"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Felipa Silvana Trump"
                        },
                        new
                        {
                            AlumnoID = new Guid("07b2af25-1897-423a-adf3-52efd2376d64"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Donald Freddy Trump"
                        },
                        new
                        {
                            AlumnoID = new Guid("07fc6f18-0a33-44d8-b31e-3a867cc6b7ac"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Eusebio Silvana Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("002c7b8d-b2fa-4a63-8e70-225b6865ab55"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Alvaro Teodoro Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("009bfb2a-18b7-41d1-ab8e-af5f5a1d0588"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Alvaro Murty Maduro"
                        },
                        new
                        {
                            AlumnoID = new Guid("012506ed-fe50-4bd6-a487-c7e8cb8f68bf"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Nicolás Nicomedes Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("01537ab2-b7b4-47b2-9d13-531c59b3c22c"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Nicolás Silvana Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("02f1ccf4-1322-4916-8807-a55777775939"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Farid Diomedes Uribe"
                        },
                        new
                        {
                            AlumnoID = new Guid("03680b19-8dd0-4911-9987-798242ae3fb0"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Alvaro Murty Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("048ac994-62cb-458b-af93-6a0de12c4a45"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Felipa Nicomedes Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("04984ca7-6116-49bb-852f-c86130130a90"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Donald Silvana Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("051fe1d2-4ab7-4b5b-8d7f-f36d9c84fed2"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Alvaro Diomedes Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("071da8b4-0dde-4616-8144-acf6624156c5"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Donald Diomedes Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("074b3cbf-7fae-491d-a684-fd58046dd6f3"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Felipa Freddy Maduro"
                        },
                        new
                        {
                            AlumnoID = new Guid("0aa008c3-c618-4377-90c5-a0a21d9aa4ed"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Alvaro Anabel Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("0c243149-bff9-4ff3-b467-e684d4f7e636"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Nicolás Anabel Maduro"
                        },
                        new
                        {
                            AlumnoID = new Guid("0c7dceaf-4d82-44e3-8a8b-f558e8bd3b48"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Farid Diomedes Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("0d5f8179-5628-497e-8605-232e03b0b29b"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Eusebio Murty Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("0e0f126c-d0b5-4494-8f75-896795855bb4"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Eusebio Nicomedes Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("0e9d9871-a4a8-4f79-bdbc-2a35a02b497e"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Donald Silvana Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("0047d664-b591-486b-92d0-1dfa1eb770c2"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Donald Freddy Toledo"
                        },
                        new
                        {
                            AlumnoID = new Guid("01ed7800-bc62-4e9b-ab12-6ca764468e54"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Nicolás Rick Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("022e9a19-5566-4b0c-97df-2420fb1694e1"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Felipa Anabel Sarmiento"
                        },
                        new
                        {
                            AlumnoID = new Guid("025e5e1e-ad4d-477d-8640-dec619b81d0d"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Alba Diomedes Herrera"
                        },
                        new
                        {
                            AlumnoID = new Guid("03942a93-52e0-47e8-9992-995f360ba5b3"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Alvaro Anabel Trump"
                        },
                        new
                        {
                            AlumnoID = new Guid("03f36db3-8a56-4421-8b68-7f92b968ea7b"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Nicolás Rick Ruiz"
                        },
                        new
                        {
                            AlumnoID = new Guid("044bfc4b-5bfb-4891-9889-59184532dac4"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Alvaro Silvana Maduro"
                        },
                        new
                        {
                            AlumnoID = new Guid("059f2654-82d5-4f14-b46b-9e5505e8acb9"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Alvaro Murty Sarmiento"
                        });
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Asignatura", b =>
                {
                    b.Property<Guid>("AsignaturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CursoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AsignaturaID");

                    b.HasIndex("CursoID");

                    b.ToTable("Asignatura", (string)null);

                    b.HasData(
                        new
                        {
                            AsignaturaID = new Guid("a2329dac-ea7e-49d2-a832-34ae3c8170e9"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            AsignaturaID = new Guid("5a771a95-15de-442f-aaa0-73fd702155b1"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            AsignaturaID = new Guid("50bb22c5-0ca7-43ce-8af7-85b7b8e4cb22"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Castellano"
                        },
                        new
                        {
                            AsignaturaID = new Guid("4537dcd8-3a8a-4710-b607-09201b8c9526"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            AsignaturaID = new Guid("0723042f-794e-4068-b019-14647ae53b44"),
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            Nombre = "Programación"
                        },
                        new
                        {
                            AsignaturaID = new Guid("c70c125d-8fe2-4751-8cd7-29f827cf6bfb"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            AsignaturaID = new Guid("08d6c22d-8d37-4267-a386-623fe1ce3be8"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            AsignaturaID = new Guid("cbfe5291-9635-4b62-a89e-9c1d5a883791"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Castellano"
                        },
                        new
                        {
                            AsignaturaID = new Guid("0f9f90de-0f5a-4a5d-89c5-6cc98d9ff8da"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            AsignaturaID = new Guid("230dd8fb-a3a8-4396-aca5-b11cd03472f3"),
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            Nombre = "Programación"
                        },
                        new
                        {
                            AsignaturaID = new Guid("30605797-af64-41ef-b444-5f7eefee8ace"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            AsignaturaID = new Guid("b4fe762d-f9a6-41cf-9db0-57d40166adcc"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            AsignaturaID = new Guid("7beef989-62ad-40bf-a542-6168bf93ad0c"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Castellano"
                        },
                        new
                        {
                            AsignaturaID = new Guid("868861f5-31ef-416c-b749-f176eec55b37"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            AsignaturaID = new Guid("89d0a4fa-a0ec-41b9-a449-55de3cff33ff"),
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            Nombre = "Programación"
                        },
                        new
                        {
                            AsignaturaID = new Guid("5bf9fab8-f815-4ab8-b8a9-cda1159d6c84"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            AsignaturaID = new Guid("5dec46c8-1a4c-4171-8066-35c32b98145b"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            AsignaturaID = new Guid("c1319eac-675b-4705-85e2-49aaa089525c"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Castellano"
                        },
                        new
                        {
                            AsignaturaID = new Guid("fd29d3b3-7d0c-4652-9b87-e8fe69f9819c"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            AsignaturaID = new Guid("005e9755-96e0-4ef7-a397-7fde4d756a83"),
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            Nombre = "Programación"
                        },
                        new
                        {
                            AsignaturaID = new Guid("e0786d14-1106-44ed-9d8d-17d0c62a2a77"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            AsignaturaID = new Guid("5c466535-e2cc-473b-9141-b69a21c7a035"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            AsignaturaID = new Guid("bbaaaa83-3512-482f-9838-cebbc4a3e07b"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Castellano"
                        },
                        new
                        {
                            AsignaturaID = new Guid("55710379-7d2d-476c-a4bc-d835efd8871f"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            AsignaturaID = new Guid("c4ce22c0-1223-46ac-896f-4173c34c1740"),
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            Nombre = "Programación"
                        });
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Curso", b =>
                {
                    b.Property<Guid>("CursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EscuelaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Jornada")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoID");

                    b.HasIndex("EscuelaID");

                    b.ToTable("Curso", (string)null);

                    b.HasData(
                        new
                        {
                            CursoID = new Guid("cded5de9-aefe-4dce-8e7c-145f4efb1d03"),
                            EscuelaID = new Guid("cc83452c-1602-438d-9364-2ff4d42932ee"),
                            Jornada = 0,
                            Nombre = "101"
                        },
                        new
                        {
                            CursoID = new Guid("a20f88fc-b1d5-4b96-aae1-710b1e6b7159"),
                            EscuelaID = new Guid("cc83452c-1602-438d-9364-2ff4d42932ee"),
                            Jornada = 0,
                            Nombre = "201"
                        },
                        new
                        {
                            CursoID = new Guid("17a88bc1-d80a-45ae-951a-ba9cbef3191e"),
                            EscuelaID = new Guid("cc83452c-1602-438d-9364-2ff4d42932ee"),
                            Jornada = 0,
                            Nombre = "301"
                        },
                        new
                        {
                            CursoID = new Guid("638b9110-3cef-405d-a936-87d2fe379845"),
                            EscuelaID = new Guid("cc83452c-1602-438d-9364-2ff4d42932ee"),
                            Jornada = 1,
                            Nombre = "401"
                        },
                        new
                        {
                            CursoID = new Guid("97cebf4c-6624-41ac-b35f-742d88229d62"),
                            EscuelaID = new Guid("cc83452c-1602-438d-9364-2ff4d42932ee"),
                            Jornada = 1,
                            Nombre = "501"
                        });
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Escuela", b =>
                {
                    b.Property<Guid>("EscuelaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnioDeCreacion")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoEscuela")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("EscuelaID");

                    b.ToTable("Escuela", (string)null);

                    b.HasData(
                        new
                        {
                            EscuelaID = new Guid("cc83452c-1602-438d-9364-2ff4d42932ee"),
                            AnioDeCreacion = 2005,
                            Ciudad = "Bogota",
                            Direccion = "Avd Siempre viva",
                            Nombre = "Platzi School",
                            Pais = "Colombia",
                            TipoEscuela = 1
                        });
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Evaluacion", b =>
                {
                    b.Property<Guid>("EvaluacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlumnoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsignaturaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Nota")
                        .HasMaxLength(4)
                        .HasColumnType("real");

                    b.HasKey("EvaluacionID");

                    b.HasIndex("AlumnoID");

                    b.HasIndex("AsignaturaID");

                    b.ToTable("Evaluacion", (string)null);
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Alumno", b =>
                {
                    b.HasOne("aspNetCoreEscuela.Models.Curso", "Curso")
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Asignatura", b =>
                {
                    b.HasOne("aspNetCoreEscuela.Models.Curso", "Curso")
                        .WithMany("Asignaturas")
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Curso", b =>
                {
                    b.HasOne("aspNetCoreEscuela.Models.Escuela", "Escuela")
                        .WithMany("Cursos")
                        .HasForeignKey("EscuelaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Evaluacion", b =>
                {
                    b.HasOne("aspNetCoreEscuela.Models.Alumno", "Alumno")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AlumnoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspNetCoreEscuela.Models.Asignatura", "Asignatura")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AsignaturaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Alumno", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Asignatura", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Curso", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("aspNetCoreEscuela.Models.Escuela", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
